version: '3.4'

services:
  cleanarchtemplate.server:
    image: ${DOCKER_REGISTRY-}cleanarchtemplateserver
    build:
      context: .
      dockerfile: src/Server/Dockerfile
    depends_on:
      - cleanarchtemplate.db
    #environment:
      #DefaultConnection: "Server=cleanarchtemplate.db;Database=myDb;User Id=sa;Password=Qwerty12345*;"

  cleanarchtemplate.db:
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      SA_PASSWORD: "Qwerty12345*"
      ACCEPT_EULA: "Y"